In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
print("1 : ", a[1][2])

print("2 : ", a.shape)

print("3 : ", a.size)

print("3 : ", a.size)

print("4 : \n", np.zeros((4,2)))

print("5 : ", np.arange(3, 12, 2))

1 :  6
2 :  (3, 3)
3 :  9
3 :  9
4 : 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8 ,9], [10, 11, 12]])

print("6 : ", np.concatenate((x, y), axis=1))
print("7 : ", np.concatenate((x, y), axis=0))
print("8 : ", np.vstack((x, y)))

6 :  [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
7 :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
8 :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
a = np.arange(10)
print("9 : ", a.reshape(5,2))
print("10 : ", a.reshape(2,-1))

9 :  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
10 :  [[0 1 2 3 4]
 [5 6 7 8 9]]


In [15]:
a = np.array([1, 2, 3, 4, 5, 6,7,8])
print("11 : ", a.shape)
a1 = a[np.newaxis, :]
print("12 : ", a1)
print("13 : ", a1.shape)
a2 = a[:, np.newaxis]
print("14 : ", a2)
print("15 : ", a2.shape)

11 :  (8,)
12 :  [[1 2 3 4 5 6 7 8]]
13 :  (1, 8)
14 :  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
15 :  (8, 1)


In [1]:
import chromadb

client = chromadb.HttpClient(
    host="mywol.iptime.org",
    port=3307
)

print(client.heartbeat())

1742964902526117310
