아래 문제들은 결과 출력까시 실행 후 노트북 파일을 제출

1.1차원이면서 크기가 10이고 0으로 채워진 배열을 생성하고 다섯번째 요소를 1로 설정하는 코드를 작성하시오.

In [3]:
import numpy as np

a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

2.아래와 같은 배열을 생성하는 code를 작성하시오.
arange 사용

[3,6,9,12,15,18,21]

In [4]:
import numpy as np

a = np.arange(3, 22, 3)
a

array([ 3,  6,  9, 12, 15, 18, 21])

3.0부터 8까지의 값을 가지고 크기가 3x3인 행렬을 arange와 reshape 명령어를 이용하여 생성 하시오.

[[0 1 2]    
 [3,4,5]  
 [6,7,8]]


In [9]:
import numpy as np

a = np.arange(0, 9)
print(a.reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4.난수로 채워진 3x3 배열을 생성하고 최대값과 최소값을 구하는 코드를 작성 하시오

In [12]:
import numpy as np

a = np.random.rand(3, 3)
print("최대값 : ", a.max())
print("최소값 : ", a.min())

최대값 :  0.9689150116331184
최소값 :  0.031648180569070705


5.다음과 같은 행렬을 만드는 code를 작성하시오.
(ones 함수와 slicing 이용)

[[1,1,1,0,0]    
  [1,1,1,0,0]  
  [1,1,1,0,0]   
  [1,1,1,1,1]]

In [25]:
import numpy as np

a = np.ones([4, 5])
a[:3, 3:5] = 0
a

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1.]])

6.5x5 행렬을 만들어 체크보드 패턴으로 채워보자
( zeros 함수와 slicing 이용)

[[0,1,0,1,0]  
[1,0,1,0,1]  
[0,1,0,1,0]  
[1,0,1,0,1]  
[0,1,0,1,0]]  

In [81]:
import numpy as np

a = np.ones([5, 5])

a[0:5:2, 0:5:2] = 0
a[1:5:2, 1:5:2] = 0

a


array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

7.5x5 행렬을 만들어 아래와 같은 패턴으로 채워보자 ( zeros 함수와 slicing 이용)

[[0,0,0,0,0]  
[1,1,1,1,1]  
[0,0,0,0,0]  
[1,1,1,1,1]  
[0,0,0,0,0]]  

In [89]:
import numpy as np

a = np.ones([5, 5])
a[::2] = 0
a

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

8.다음 배열이 가장 자리만 0이 되도록 변경 하시오.


In [96]:
import numpy as np
a = np.ones((10,10))
a[::9] = 0
a[:, ::9] = 0
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

9.아래 a에서  
1) 10보다 값이 큰 원소의 인덱스 print  
2) 값이 0인 원소의 인덱스 print   


In [62]:
import numpy as np
a = np.array([3,6,2,0,5,8,15,3,0,6,0])

print(np.where(a>10))
print(np.where(a==0))

(array([6]),)
(array([ 3,  8, 10]),)


10.아래 code실행 후 a를 print했을때 아래와같이 나오도록 code를 추가 하시오.  
[ 9  8 10  9]

In [ ]:
import numpy as np
a = np.array([9, 2, 3,4, 8, 7, 10, 9])
a[a>=8]

array([ 9,  8, 10,  9])