반: A
학번: 202044004  
이름: 안태민


In [7]:
from tensorflow import keras
from keras.models import load_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

#데이터를 불러 옵니다.
df = pd.read_csv("house_data.csv")

#카테고리형 변수를 0과 1로 이루어진 변수로 바꾸어 줍니다.(12장 3절)
df = pd.get_dummies(df)

#결측치를 전체 칼럼의 평균으로 대체하여 채워줍니다.
df = df.fillna(df.mean())

#업데이트된 데이터프레임을 출력해 봅니다.
#df
#집 값을 제외한 나머지 열을 저장합니다.
cols_train=['OverallQual','GrLivArea','GarageCars','GarageArea','TotalBsmtSF']
X_data = df[cols_train]
X_data=X_data.astype(float)
scaler = MinMaxScaler()
scaler.fit(X_data)

print(X_data.shape)

print(scaler.transform(X_data))

(1460, 5)
[[0.66666667 0.25923135 0.5        0.3864598  0.1400982 ]
 [0.55555556 0.17483044 0.5        0.32440056 0.20654664]
 [0.66666667 0.27354936 0.5        0.42877292 0.15057283]
 ...
 [0.66666667 0.37792012 0.25       0.17771509 0.18854337]
 [0.44444444 0.14016579 0.25       0.16925247 0.17643208]
 [0.44444444 0.17370008 0.25       0.19464034 0.20556465]]
